[package]
name = "zenpull-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
async-channel = "2.3.1"
clap = "4.5.20"
reqwest = { version = "0.12.9", features = ["blocking"] }
spmc = "0.3.0"
tokio = { version = "1.41.0", features = ["full"] }
